sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: c1ioDHiKh+k/S40PrcwXjPdG4i/xf+s9nZC01rFgo8YE5KGUOEFQhNXsORUjazOAv6HTDSFazcBAkVl0e5f5i0uxK3n4rlombkvTYoohZs74Ilb1frrJupRDyY3Z2YDQvmWTEE7EEZwocp13xzIPzjyE6p4UGLM09t1Xx/6dCtz8E0Qeuzfl6+5nYabfsgcEWFVtONGhTccVI7zGQmfEVK+4+e4zQdOuagsJ2df8PCtl5vql9zYX5ZpGlaFiL6QqZD88m5wz1mcc7EWIVauDd9tvqrMi6zErfgH3E2yA5YkgjUVo1H19pDUKK6Uww2eWZ7rSQ+3TLb/e2idFVUiNF07iTKga60tu3Qh61rXheQrj6FdyS1xWFPwI8MYWmne6v+w1ffALttXdiMVQ25bCRR4pJsFQvlhBK25WlxudpbVess0dRFkdeFZUFneecBaBx7pGwgvV6WITwNz5nGXqbOIWMjtvskcdsiMiTOFicFEkvb2ek2SKpJrUxksViVAfujkb+FLmHBJqhbNEnzKhBzRL2edY1VEWe5rHZNW6I8uZovVXu4d1Jc1oGYK8i+cGdqxIBmn+vlOAAYvajcjGFFbUYHkMlzMgKd2KCk+MZxg+t91OCIaOvzmD4mYN1/HqazGyxUkmjaUura5PcU7+2pLK6FWIaf49UA49SFHvGzs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Karl-Ludwig-Sand--13-Celebrated-Crimes_2745
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy